//CALCOLARE IL PREZZO DEL BIGLIETTO IN BASA ALLA TRATTA E ETA' PASSEGGERO

//INPUT (VARIABILI E DATI IN INGRESSO)
    //CHIEDIAMO A USER LA TRATTA ESPRESSA IN KM
    //CHIEDIAMO L'ETA' DI USER

//ELABORAZOINE
    //CALCOLO LA TARIFFA IN EURO (CONVERTO I KM IN EURO ; 021$ A KM)
    //VERIFICO ETA'
        //SE USER HA ETA'<= A 18 (SCONTO 20%)
        //SE USER HA ETA'>= A 65 (SCONTO 40%)

//OUTPUT(PREZZO FINALE CON NON PIù DI DUE CIFRE DECIMALI)